language: ruby
dist: trusty
rvm:
- 2.5
before_install:
  - yes | gem update --system --force
  - gem install bundler:2.2.24
branches:
  only:
  - master
before_script:
  - chmod +x ./script/cibuild
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./script/cibuild"
exclude:
- vendor
sudo: false
env:
  global:
  - secure: QK9SJcrSQea4qsvbSOLsrw+8rEt+6QfT4gZezdWsUp0XSIEiVLA/yNrxBIIcaWiobo/+ur3p0I1OM6uJmiDI6YQNlUurORmj9ju9fVSywzF745V2xIGsN5Q7fOoZZ5wiPrVocM2v6henU5JR6br25iquZHJAONuYLRuFt6mOlPX80XExK2sJMk6oyQIstrpCbsMN6LHcuxv1oXpMDNsB2lQA7Jt0ghYfJqSsdO1buKUN6G9jv1WiiUxdb5GZ2Heav3Tvl/3fjc1vfz51Vq17AL/2CWu2xgvrhaVdwyXAiFMdLp0TKry96KllLW7rnw6q9JfM7c5N/AARl+f1gTmJW0nT/yHBQ+2aPyZb+ITChq9aJHDfUczLD2CeYOgoPqoZ4U3d7R08hNiYnWB8Y9Dd3HHaftFkAYnPcATOvx4xGledTis/zRJq8nPO7mttrC/YR29HBBGlAGVf2WavQakERoSxoOq3+28tDwwmchbZ8GPqOK7GmHesyZ0jGRGYpWoTXJuXmQcSTC6RDg1em2OcUZA3Z8hMIHHipnjHMOclFzOu4BpT6PZbWywjiknG6KV0rvKZhn1/5Jk+L8L2rEG8WJM7BOGsGnL40YP/5Q1sinb3TcLK2itIm9uBCLsi71lwZNIm9i1YWnF75daocqchW8zX1Z9eBuCYWfreblP28ZQ= 
  jobs:
  - USE_NETWORK=true
  - USE_NETWORK=false
  - secure: "<you can also put encrypted vars inside matrix>"