# Setup
title:               don's TILğŸ™ğŸ»
tagline:             blog
description:         ì˜¤ëŠ˜ë³´ë‹¤ ë‚˜ì€ ë‚´ì¼ì„ ì‚´ ìˆ˜ ìˆê¸°ë¥¼
url:                 https://dondon17.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
logo:                '/public/apple-touch-icon-precomposed.png'

# About/contact
author:
  name:              DOWOON KIM
  url:               https://github.com/dondon17
  contact:
    email:           qwerqw889@ajou.ac.kr
    github:          https://github.com/dondon17
    facebook:        https://www.facebook.com/25dons

# Gems
plugins:
  - jekyll-paginate

# Custom vars
mathjax: true
google_analytics_token: ''
google_analytics_id: #UA-XXXX-Y

category_dir: category/
tag_dir: tag/
