# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Murat Şentürk
tagline:             'Blog'
description:         ''
url:                 #
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Murat Şentürk
  url:               #
  email:             mrtsenturk@gmail.com

# Custom vars
version:             1.0.0
