# Dependencies
markdown:         redcarpet
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Kyle Schmidt'
tagline:          'Software Craftsman'
description:      'Musings about Python, Emacs, JavaScript (React/Redux), and Databases as well as a few health & fitness posts.'
url:              http://k-schmidt.github.io

author:
  name:           'Kyle Schmidt'
  url:            https://twitter.com/kyle_schmidt

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/k-schmidt
linkedin:         https://www.linkedin.com/in/kylealanschmidt
twitter:          https://twitter.com/Kyle_Schmidt

gems:
  - jekyll-paginate
