# Setup
title:               payvision development
tagline:             'House of engineers'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://leonardopoza.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Payvision Development
  url:               https://payvision.com
  email:             l.poza@payvision.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
