# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://j31d0.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Park jihee
  url:               https://j31d0.github.io
  email:             j31d0@kaist.ac.kr

# Custom vars
version:             1.0.0
