# Setup
title:               The ICLR Blog Track
tagline:             ''
description:         'For short-term, peer-sourced tests of time, generalizations, specializations, reproductions, etc.!'
url:                 https://iclr-blog-track.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# github
github:
  repo: https://github.com/iclr-blog-track/iclr-blog-track.github.io

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             ICLR Spring 2021
google_analytics_id: #UA-XXXX-Y
