# Setup
title:               Melania S. Masià
# tagline:             ''
description:         'Linguistics | Academic site of Melania Sánchez Masià'
url:                 https://sanmame.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Melania S. Masià
  email:             melaniasanchezmasia@gmail.com
  twitter:           melaniasmasia

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: UA-57130680-2
