# Setup
title:               Noah Kennedy
tagline:             'Based in D.C.'
description:         'Chemical Engineer by education, Data Engineer by trade. I geek out on biotech, endurance sports, and good coffee.'
url:                 https://noahkennedy.co
baseurl:             ''
permalink:           pretty

# Pagination
pagination:
  enabled: true
  debug: false
  collections: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'release_date'

# About/contact
author:
  name:              Noah Kennedy
  url:               https://github.com/noahfkennedy
  email:             noah.kennedy1@gmail.com@gmail.com

# Gems
plugins:
  - jekyll-paginate-v2

# Custom vars
version:             1.1.0. Still working on NK.v.2
google_analytics_id: UA-146052-15
