# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               The R class
tagline:             'An introduction to programming using R'
description:         'A course to learn how to develop reproducible and collaborative workflows using R.'
url:                 http://fmichonneau.github.io/r-class
baseurl:             /r-class
paginate:            5

# About/contact
author:
  name:              Fran#&231;ois Michonneau
  url:               http://francoismichonneau.net
  email:             francois.michonneau@gmail.com

# Custom vars
version:             1.0.0
