# Dependencies
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Learning Java/JavaEE
tagline:             'Blog about my Java/JavaEE experiences'
description:         'Blog about my Java/JavaEE experiences'
url:                 http://cchacin.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Carlos Chacin
  url:               https://twitter.com/carloschacin
  email:             cchacin@gmail.com

# Custom vars
version:             1.0.0
