# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               dtsbourg
tagline:             'Dylan Bourgeois'
description:         'I am a microengineering student @EPFL. Find me on Twitter <a href="https://twitter.com/dtsbourg" target="_blank">@dtsbourg</a>.'
url:                 http://dtsbourg.github.io
baseurl:             http://dtsbourg.github.io
paginate:            5

# About/contact
author:
  name:              Dylan Bourgeois
  url:               https://twitter.com/dtsbourg
  email:             dtsbourg@gmail.com
  locale:            Lausanne, Switzerland

# Analytics
google_analytics:    UA-65856095-1
