# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title: 'Ladies First!'
tagline: 'an annotated digital edition'
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
url:
baseurl: ''
# Generate static export with relative links
# Should NOT be used with a baseurl configured
relative_links: false

homepage_image: http://readux.library.emory.edu/books/emory:7sr72/pages/emory:gmrpr/single-page/

# About/contact
author:
  name: An Author
  url:
  email:

# Custom vars
version:             1.0.0


# readux export specifics
show_annotation_author: true

source_info:
  title: '"Ladies first!"  a novel'
  author: Verdenal, Dominique François, Mrs.
  date: '1896'
  url: 'http://readux.library.emory.edu/books/emory:7sr72/'
  pdf_url: 'http://readux.library.emory.edu/books/emory:7sr72/pdf/#page=2'
  via_readux: true

publication_info:
  title: 'Ladies first!, an annotated edition'
  author: Verdenal, Dominique François, Mrs.
  editors:
    - "Tater, Anne O."
  date: 2015
  # publisher: "Some institute"
  # rights: "Some rights reserved."

# optional: set thumbnail page size to tune page browse display
# image_size:
#   thumbnail:
#     width:
#     height:


collections:
    annotations:
        output: true
    volume_pages:
        output: true
        permalink: /pages/:path/

defaults:
  - scope:
      path: ""
      type: volume_pages
    values:
      layout: volume_page
      short_label: 'p.'
      extra_js:
        - deepzoom.js
        - openseadragon.min.js
        - volume-page.js



