# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title: 'Ladies First!'
tagline: 'an annotated digital edition'
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
url:
baseurl: ''

homepage_image: http://readux.library.emory.edu/books/emory:7sr72/pages/emory:gmrpr/single-page/

# About/contact
author:
  name:
  url:
  email:

# Custom vars
version:             1.0.0


# readux export specifics
show_annotation_author: true

readux_url: 'http://readux.library.emory.edu/books/emory:7sr72/'
readux_pdf_url: 'http://readux.library.emory.edu/books/emory:7sr72/pdf/#page=2'

collections:
    volume_pages:
        output: true
        permalink: /pages/:path/
    annotations:
        output: false

defaults:
  - scope:
      path: ""
      type: volume_pages
    values:
      layout: volume_page
