# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blockchain Global Compliance Hub
tagline:             'Your source for blockchain compliance around the world'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://mimush.github.io/NEOtest
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Miryam Amsili
  url:               https://twitter.com/neo_blockchain
  email:             miryam.amsili@gmail.com

# Custom vars
version:             1.0.0
