
# Setup
title:                          liamOS
tagline:                        'An iOS development blog'
description:                    ''
url:                            https://liamnichols.github.io
baseurl:                        ''
paginate:                       5
highlighter:                    rouge
google_analytics_tracking_id:   UA-83930015-1


# Gems
gems:                 [jekyll-paginate]

# About/contact
author:
  name:               Liam Nichols
  url:                https://twitter.com/liamnichols_
  email:              liam.nichols.ln@gmail.com
